### ISSUE TITLE
cargo cannot download packages

### ISSUE THREAD

**Issue by casept** [its-pointless/gcc_termux#10]
Anytime I try to download a package from the crates registry I get the following error:
```
invalid Content-Type: application/x-git-upload-pack-advertisement
```

Manually cloning the `crates.io-index` repo works fine.

**Comment by its-pointless** [comment]
Yeah iv been trying to bug fix this.... 
With the the recent move to libc++ all sorts of weird things are happening especially on arm. This bug doesn't exist for aarch64.

**Comment by its-pointless** [comment]
here is a fix that will allow you to get cargo to work https://github.com/its-pointless/its-pointless.github.io/raw/master/files/libgit2shit.deb
its basically just different cflags.
I tried to debug it and then it works no debugging required...

**Comment by its-pointless** [comment]
better one 
[url "git://github.com/rust-lang/crates.io-index"]
        insteadOf = https://github.com/rust-lang/crates.io-index

**Comment by casept** [comment]
Your workaround worked, thanks!

**Comment by NeckRevolution** [comment]
Hello i am faced whit this error
Welcome to Termux!

Online help:     https://termux.com/help
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ curl -L https://its-pointless.github.io/setup-pointless-repo.sh | sh
sh: 1: The: not found
Hit:1 http://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libcurl libnghttp2
The following NEW packages will be installed:
  curl libcurl libnghttp2
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 304 kB of archives.
After this operation, 897 kB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
$

**Comment by its-pointless** [comment]
No need for -L

**Comment by NeckRevolution** [comment]
Thx the main problem source is that the curl isn't installed. After installation everithing worked  :)

**Comment by NeckRevolution** [comment]
Thx the main problem source is that the curl isn't installed. After installation everithing worked  :)

**Comment by its-pointless** [comment]
Updated cargo should work now

**Comment by casept** [comment]
Seems to still be broken on my device (Galaxy S4 VE (ARM) running lineageOS 14) :(.

I still get the same `Invalid Content-Type: application/x-git-upload-pack-advertisment` error as I did previously.

**Comment by its-pointless** [comment]
Try updating now
It should be fixed?

**Comment by casept** [comment]
Seems to be fixed now, thanks a lot!
