### ISSUE TITLE
numpy, scipy broken in latest update

### ISSUE THREAD

**Issue by yubrajbhoi** [its-pointless/gcc_termux#80]
```
arch=arm
Android version=8.1.0
```
This is the error:
```
Original error was: dlopen failed: cannot locate symbol "__aeabi_f2ulz"
```
Seems to be this issue:
https://github.com/android/ndk/issues/126

**Comment by its-pointless** [comment]
oh right forgot --as-needed is added to ldflags in current python
meaning its not linking libcompiler_rt.so 
will fix it in a bit but if you are impatient you can add /system/lib/libcompiler_rt.so to LD_PRELOAD

**Comment by its-pointless** [comment]
and should be fixed now

**Comment by yubrajbhoi** [comment]
Thank you. Forgot to check closed issues.

**Comment by muhymenulhaque** [comment]
This problem is still not fixed. So had to go through a lots of google search. Hope you  will fix it soon. The error with me was when scipy is imported it would give the error of :
dlopen failed: cannot locate symbol "__aeabi_f2ulz"
