### ISSUE TITLE
Symbolically link GNAT's shared libs

### ISSUE THREAD

**Issue by umarcor** [its-pointless/gcc_termux#84]
I found symbolically linking `libgnat-9.so` and `libgnarl-9.so` to be required in order to build a tool written in Ada. These libraries are located in `$PREFIX/lib/gcc/aarch64-linux-android/9.2.0/` and there are symbolic links named `libgnat.so` and `libgnarl.so` in the same directory. However, these are not found unless `LD_LIBRARY_PATH` is set. Alternatively, the following links work:

```sh
ln -s $PREFIX/lib/gcc/aarch64-linux-android/9.2.0/libgnat-9.so $PREFIX/lib/libgnat-9.so
ln -s $PREFIX/lib/gcc/aarch64-linux-android/9.2.0/libgnarl-9.so $PREFIX/lib/libgnarl-9.so
```

I'd like to request that the creation of these symbolic links is added to the installation of package gnat-9.

**Comment by its-pointless** [comment]
done

**Comment by umarcor** [comment]
@its-pointless, I tried the following:

```sh
rm $PREFIX/lib/libgnat-9.so
rm $PREFIX/lib/libgnarl-9.so
pkg uninstall gnat-9 gcc-9

curl -fsSL https://its-pointless.github.io/setup-pointless-repo.sh | bash -
pkg install gnat-9
setupgcc-9
```

Unfortunately, I get `library "libgnat-9.so" not found`. Hence, it seems that either this issue is not fixed or I'm not updating it as expected. Any hint is welcome.

**Comment by its-pointless** [comment]
Its in libgnat

**Comment by umarcor** [comment]
Package `libgnat` does not exist. `libgnat-9` does exist, and it is installed as a dependency of `gnat-9`. Moreover, I tried manually reinstalling `libgnat-9`. Still, symbolic links are not found. `$PREFIX/lib/libgnat.so` and `$PREFIX/lib/libgnarl.so` exist only, neither `libgnat-9.so`, nor `libgnarl-9.so` are found in `$PREFIX/lib`.

**Comment by its-pointless** [comment]
https://github.com/its-pointless/its-pointless.github.io/raw/master/files/24/dists/termux/extras/binary-aarch64/libgnat-9_9.3.0_aarch64.deb 
i just downloaded that. extracted it and it contains correct symlinks.

**Comment by umarcor** [comment]
You are correct. Apparently, something didn't update as expected because some issue with the key. I now executed `curl -fsSL https://its-pointless.github.io/setup-pointless-repo.sh | bash -` again, then `apt update` and `apt upgrade`. Everything looks good now. Thanks!
